### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by elpoto** [DigitalPublishingToolkit/epubster#2]
This looks interesting!
Is there a demo available somewhere?

**Comment by almereyda** [comment]
Yup, I was just about to ask the same question. Or screenshots at least so one knows its worth the effort to deploy it?

**Comment by mensch** [comment]
I've uploaded some screenshots to the repository. Setting up a demo server isn't feasible at the moment, I'm afraid.

**Comment by elpoto** [comment]
Thank you.
It sees the full sizes have the same size as the thumbnails.

**Comment by mensch** [comment]
Should be fixed now!

**Comment by elbotho** [comment]
Top!
